apiVersion: v1
kind: Pod
metadata:
  name: annotations
    imageregistry: "https://hub.docker.com/"
    buildURL: "https://jenkins.cheswin.shop/expense/backend/build/67"
spec:
  containers:
  - name: nginx
    image: nginx    




