apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels:
    project: expense
    module: backend
    envinorment: dev
spec:
  containers:
  - name: nginx
    image: nginx
kind: Service
apiVersion: v1
metadata:
   name: nginx
spec:
   selector:
   project: expense
   module: backend
   envinorment: dev
ports:
   - name: nginx-svc-port
     protocol: TCP
     port: 80
     targetPort: 80 # container port number   
