apiVersion: app/v1
kind: ReplicaSet
metadata:
   name: nginx
   labels:
     app: nginx
     tier: frontend
spec:
  replicas: 3
  selectors:
     matchlabels:
        app: nginx
        tier: frontend
templete:
   metadata:
     labels:
       app: nginx
       tier: frontend
spec:
conatiners:
- name: nginx
  image: nginx
