apiVersion: apps/v1
kind: Deployment
metadata:
   name: nginx
   labels:
     app: nginx
     tier: frontend
spec:
  replicas: 3
  selector:
    matchlabels:
       app: nginx
       tier: frontend
templete:
   metadata:
      labels:
        tier: frontend
        app: nginx
spec:
   containers:
   - name: nginx
     image: nginx
---
kind: Service
apiVersion: v1
metadata:
   name: nginx
spec:
  selector:
    tier: frontend
    app: nginx
ports:
- name: nginx-svc-port
  protocol: TCP
  ports: 80
  targetPort: 80   
